### ISSUE TITLE
Impossible to install phpdocumentor/reflection-docblock ^3.0.3 as the version 4.1.1 is already installed

### ISSUE THREAD

**Issue by Croxarens** [googleads/googleads-php-lib#370]
I know that the kind of error I have is tied to the project where I'd like to use the googleads-php-lib, but from the moment the latest version of phpdocumentor/reflection-docblock seems to be 4.1.1, I was wondering if is there any specific reason why the googleads-php-lib is using the ^3.0.3 instead of the latest.

```
composer require googleads/googleads-php-lib
Using version ^30.0 for googleads/googleads-php-lib
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for googleads/googleads-php-lib ^30.0 -> satisfiable by googleads/googleads-php-lib[30.0.0].
    - Conclusion: remove phpdocumentor/reflection-docblock 4.1.1
    - Conclusion: don't install phpdocumentor/reflection-docblock 4.1.1
    - googleads/googleads-php-lib 30.0.0 requires phpdocumentor/reflection-docblock ^3.0.3 -> satisfiable by phpdocumentor/reflection-docblock[3.0.3, 3.1.0, 3.1.1, 3.2.0, 3.2.1, 3.2.2, 3.2.3, 3.3.0].
    - Can only install one of: phpdocumentor/reflection-docblock[3.0.3, 4.1.1].
    - Can only install one of: phpdocumentor/reflection-docblock[3.1.0, 4.1.1].
    - Can only install one of: phpdocumentor/reflection-docblock[3.1.1, 4.1.1].
    - Can only install one of: phpdocumentor/reflection-docblock[3.2.0, 4.1.1].
    - Can only install one of: phpdocumentor/reflection-docblock[3.2.1, 4.1.1].
    - Can only install one of: phpdocumentor/reflection-docblock[3.2.2, 4.1.1].
    - Can only install one of: phpdocumentor/reflection-docblock[3.2.3, 4.1.1].
    - Can only install one of: phpdocumentor/reflection-docblock[3.3.0, 4.1.1].
    - Installation request for phpdocumentor/reflection-docblock (locked at 4.1.1) -> satisfiable by phpdocumentor/reflection-docblock[4.1.1].


Installation failed, reverting ./composer.json to its original content.
```

Is there a way I can install the googleads-php-lib without downgrade any of the module I already have in my project?

**Comment by fiboknacky** [comment]
Hello @Croxarens 

The only workaround I can see now is to use [aliasing](https://stackoverflow.com/a/39549205).

> I was wondering if is there any specific reason why the googleads-php-lib is using the ^3.0.3 instead of the latest.
I've not tested if the latest version will be compatible with our library yet. That's why I've not updated the composer.json file.
Will have a look at this and update it to the latest one if possible.

Best,
Knack

**Comment by denrz** [comment]
I have the same issue right now. Did you resolve it?

**Comment by fiboknacky** [comment]
Hello @denrz 

There is a [pull request](https://github.com/googleads/googleads-php-lib/pull/379) fixing this. I'm reviewing that and will accept it if we find no issues.

Best,
Knack

**Comment by fiboknacky** [comment]
This is now resolved by [the latest commit](https://github.com/googleads/googleads-php-lib/commit/3eb29e4c72e7b053893cf966f88ec2d82298a4a6).

**Comment by denrz** [comment]
Hi @fiboknacky . Thank you for quick feedback. 
But I'm still with the same issue.

```
denis$ composer require googleads/googleads-php-lib
Using version ^31.0 for googleads/googleads-php-lib
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for googleads/googleads-php-lib ^31.0 -> satisfiable by googleads/googleads-php-lib[31.0.0].
    - Conclusion: remove phpdocumentor/reflection-docblock 4.1.1
    - Conclusion: don't install phpdocumentor/reflection-docblock 4.1.1
    - googleads/googleads-php-lib 31.0.0 requires phpdocumentor/reflection-docblock ^3.0.3 -> satisfiable by phpdocumentor/reflection-docblock[3.0.3, 3.1.0, 3.1.1, 3.2.0, 3.2.1, 3.2.2, 3.2.3, 3.3.0].
    - Can only install one of: phpdocumentor/reflection-docblock[3.0.3, 4.1.1].
    - Can only install one of: phpdocumentor/reflection-docblock[3.1.0, 4.1.1].
    - Can only install one of: phpdocumentor/reflection-docblock[3.1.1, 4.1.1].
    - Can only install one of: phpdocumentor/reflection-docblock[3.2.0, 4.1.1].
    - Can only install one of: phpdocumentor/reflection-docblock[3.2.1, 4.1.1].
    - Can only install one of: phpdocumentor/reflection-docblock[3.2.2, 4.1.1].
    - Can only install one of: phpdocumentor/reflection-docblock[3.2.3, 4.1.1].
    - Can only install one of: phpdocumentor/reflection-docblock[3.3.0, 4.1.1].
    - Installation request for phpdocumentor/reflection-docblock (locked at 4.1.1) -> satisfiable by phpdocumentor/reflection-docblock[4.1.1].


Installation failed, reverting ./composer.json to its original content.
Deniss-MacBook-Pro:cms_theatrelandltd denis$ 
```

**Comment by fiboknacky** [comment]
Hello @denrz 

This is fixed in the master branch but not in the version 31.0.0.
Could you try:
```
composer require googleads/googleads-php-lib:dev-master
```

Best,
Knack

**Comment by denrz** [comment]
Sorry @fiboknacky, the problem remains:

```
composer require googleads/googleads-php-lib:dev-master
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for googleads/googleads-php-lib dev-master -> satisfiable by googleads/googleads-php-lib[dev-master].
    - Conclusion: remove phpdocumentor/reflection-docblock 4.1.1
    - Conclusion: don't install phpdocumentor/reflection-docblock 4.1.1
    - googleads/googleads-php-lib dev-master requires phpdocumentor/reflection-docblock ^3.0.3 -> satisfiable by phpdocumentor/reflection-docblock[3.0.3, 3.1.0, 3.1.1, 3.2.0, 3.2.1, 3.2.2, 3.2.3, 3.3.0].
    - Can only install one of: phpdocumentor/reflection-docblock[3.0.3, 4.1.1].
    - Can only install one of: phpdocumentor/reflection-docblock[3.1.0, 4.1.1].
    - Can only install one of: phpdocumentor/reflection-docblock[3.1.1, 4.1.1].
    - Can only install one of: phpdocumentor/reflection-docblock[3.2.0, 4.1.1].
    - Can only install one of: phpdocumentor/reflection-docblock[3.2.1, 4.1.1].
    - Can only install one of: phpdocumentor/reflection-docblock[3.2.2, 4.1.1].
    - Can only install one of: phpdocumentor/reflection-docblock[3.2.3, 4.1.1].
    - Can only install one of: phpdocumentor/reflection-docblock[3.3.0, 4.1.1].
    - Installation request for phpdocumentor/reflection-docblock (locked at 4.1.1) -> satisfiable by phpdocumentor/reflection-docblock[4.1.1].


Installation failed, reverting ./composer.json to its original content.
```

Maybe you need to change it to 4.1.1 last release or something like ">=4.0.0" ? I'm not sure, I'm not very experienced in Composer.

**Comment by fiboknacky** [comment]
Hi @denrz 

What's the other library that require 4.1.1?
I'd like to test it myself.

About the version syntax, I believe ^4.0.0 also covers 4.1.1 based on the [test website](https://semver.mwl.be/#?package=phpdocumentor%2Freflection-docblock&version=%5E3.0.0%20%7C%7C%20%5E4.0.0&minimum-stability=stable). 

Knack

**Comment by denrz** [comment]
I'm using Laravel 5.4 and it includes the the v4.1.1 of phpdocumentor

**Comment by fiboknacky** [comment]
Hi @denrz,

I've tried installing Laravel 5.4 using composer too, but it doesn't seem to require phpdocumentor.
Could you please check again?

Knack

**Comment by fiboknacky** [comment]
Hello @denrz,

Please try again. I've just found that Packagist doesn't update its database automatically when we updated `composer.json of `dev-master`.
This should be fine now as I could confirm this myself too.

Best,
Knack

**Comment by denrz** [comment]
Hi @fiboknacky. 

It was installed successfully now! :) Thank you very much for your help.

Best Regards,
Denis.

**Comment by fiboknacky** [comment]
Glad to hear that!

**Comment by Peace-N** [comment]
I have successifully installed it as well with: composer require googleads/googleads-php-lib:dev-master

**Comment by lnavatta** [comment]
I'm having the same problem.

Just saw the current composer.json and it doesn't have the "|| 4.0.0" on "phpdocumentor/reflection-docblock": "^3.0.3"

**Comment by fiboknacky** [comment]
Sorry for the inconvenience.
I've reverted the change back so the composer.json of dev-master now has `"phpdocumentor/reflection-docblock": "^4.0.0 || ^3.0.3"` as expected.

Please try `composer require googleads/googleads-php-lib:dev-master` again.

Knack

**Comment by Peace-N** [comment]
Please use:

```
 "require": {
    "googleads/googleads-php-lib": "dev-master"
  }
```

I have developed a Laravel Package for keywords, anyone interested just say the word .. S Basically you can just clone and follow instructions . Works Superb !!

**Comment by Sharnw** [comment]
Thanks guys, glad i came across this post as i have had the same issue.
